services:
  - type: web
    name: nexalor-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000
      - key: ADMIN_PASSWORD
        value: lvttr2010
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "*"
